[book]
title = "FujiNet Documentation"
authors = ["Benjamin Krein"]
language = "en"

[output.html]
default-theme ="dark"
sidebar-header-nav = true
no-section-label = true

[output.html.fold]
enable = true